apiVersion: v1
kind: Service
metadata:
  name: {{ include "unrelated-mcp-gateway.dataServiceName" . }}
  labels:
{{ include "unrelated-mcp-gateway.labels" . | indent 4 }}
{{- with .Values.service.data.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.data.type }}
  ports:
    - name: data
      port: {{ .Values.service.data.port }}
      targetPort: data
      protocol: TCP
  selector:
{{ include "unrelated-mcp-gateway.selectorLabels" . | indent 4 }}
