apiVersion: v1
kind: Service
metadata:
  name: {{ include "unrelated-mcp-postgres.fullname" . }}
  labels:
{{ include "unrelated-mcp-postgres.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
{{ include "unrelated-mcp-postgres.selectorLabels" . | indent 4 }}
